# List of dependencies of the project

[versions]
arrow = "2.1.2"               # https://github.com/arrow-kt/arrow/releases
kotlinx-coroutines = "1.10.2" # https://github.com/Kotlin/kotlinx.coroutines/releases
kotlinx-datetime = "0.6.2"    # https://github.com/Kotlin/kotlinx-datetime/releases
gradle-testkit = "8.11.1"     # https://gradle.org/releases/
parameterize = "0.4.0"        # https://github.com/BenWoodworth/Parameterize/releases
ktor = "3.1.3"                # https://ktor.io/docs/releases.html#release-details
kti = { strictly = "0.1.0" }  # https://gitlab.com/opensavvy/groundwork/kotlin-test-initiative/-/releases
testBalloon = "0.7.1-K2.2.0"  # https://github.com/infix-de/testBalloon/releases

[plugins]
testBalloon = { id = "de.infix.testBalloon", version.ref = "testBalloon" }

[libraries]
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-debug = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-debug", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
gradle-testkit = { module = "dev.gradleplugins:gradle-test-kit", version.ref = "gradle-testkit" }
arrow-core = { module = "io.arrow-kt:arrow-core", version.ref = "arrow" }
parameterize = { module = "com.benwoodworth.parameterize:parameterize", version.ref = "parameterize" }
ktor-testHost = { module = "io.ktor:ktor-server-test-host", version.ref = "ktor" }
kti = { module = "dev.opensavvy.kti:kotlin-test-initiative", version.ref = "kti" }
testBalloon = { module = "de.infix.testBalloon:testBalloon-framework-core", version.ref = "testBalloon" }

[bundles]
